"""Add buyer-property association

Revision ID: 992d9307ca14
Revises: b5796345c147
Create Date: 2024-09-22 17:32:30.054309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '992d9307ca14'
down_revision: Union[str, None] = 'b5796345c147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer_property_association',
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('buyer_id', 'property_id')
    )
    # op.alter_column('properties', 'agent_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'agent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('buyer_property_association')
    # ### end Alembic commands ###
